[package]
name = "roblib-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
roblib = { path = "../roblib" }
actix-http = "3"
actix-web = "4.0"
actix-rt = "2.6"
awc = "3.0.0"
futures = "0.3.21"
futures-util = "0.3.21"
bytestring = "1.0.0"
log = "0.4.14"
anyhow = "1.0.57"
env_logger = "0.9.0"

[features]
default = []

all = ["roland", "gpio", "camloc"]

roland = ["roblib/roland"]
gpio = ["roblib/gpio"]
camloc = ["roblib/camloc"]

[[example]]
name = "controller"
required-features = ["all"]

[[example]]
name = "simple"
required-features = ["all"]

[[example]]
name = "with_http"
required-features = ["all"]

[[example]]
name = "with_ws"
required-features = ["all"]
