[package]
name = "roblib-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
roblib-shared = { path = "../lib" }
actix-http = "3"
actix-web = "4.0"
actix-rt = "2.6"
awc = "3.0.0"
futures = "0.3.21"
futures-util = "0.3.21"
bytestring = "1.0.0"
log = "0.4.14"
anyhow = "1.0.57"

[features]
