[package]
name = "roblib-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
tokio-util = { version = "0.7", features = ["compat"] }
async-trait = { version = "0.1", optional = true }
tokio = { version = "1.29", features = ["net"] }
roblib-parsing = { path = "../roblib-parsing" }
roblib = { path = "../roblib" }
futures-util = "0.3"
env_logger = "0.10"
actix-http = "3.3"
actix-web = "4.3"
actix-rt = "2.8"
futures = "0.3"
anyhow = "1"
awc = "3.1"
log = "0.4"

[features]
default = []

all = ["roland", "gpio", "camloc", "async"]

async = ["roblib-parsing/async", "dep:async-trait"]

roland = []
gpio = []
camloc = []

[[example]]
name = "simple"
required-features = ["roland"]

[[example]]
name = "controller"
required-features = ["roland", "gpio", "camloc"]
