[package]
name = "roblib-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
roblib-shared = { path = "../lib" }
actix-codec = "0.3.0"
actix-http = "2.2.1"
actix-web = "3.3.3"
awc = "2.0.3"
futures-util = "0.3.19"
log = "0.4.14"

[features]
