[package]
name = "roblib_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.10" # kept at 0.10 because later versions break websockets
actix-web = "3.3.3"
actix-web-actors = "3.0.0"
env_logger = "0.9.0"
log = "0.4.14"
rppal = "0.13.1"

[features]
