[package]
name = "roblib-parsing"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { version = "0.1", optional = true }
futures = { version = "0.3", optional = true }
anyhow = "1"

[features]
default = []

all = ["async"]

async = ["dep:async-trait", "dep:futures"]
