[package]
name = "roblib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
camloc-server = { git = "https://github.com/Kris030/camloc-server", optional = true }
anyhow = "1"
lazy_static = "1.4.0"
log = "0.4"
rppal = { version = "0.13.1", optional = true }

[features]
default = []

all = ["gpio", "roland", "camloc"]

bare = []

gpio = []
roland = []
camloc = ["dep:camloc-server"]
gpio-backend = ["dep:rppal"]
