[package]
name = "roblib-server"
version = "0.1.0"
edition = "2021"

[dependencies]
roblib = { path = "../roblib" }
actix = "0.13.0"
actix-web = "4.0"
actix-web-actors = "4.1"
env_logger = "0.9.0"
log = "0.4"
lazy_static = "1.4.0"
anyhow = "1.0.59"

[features]
default = ["roland"]

all = ["roland", "gpio", "camloc"]

bare = []

roland = ["roblib/roland"]
gpio = ["roblib/gpio"]
camloc = ["roblib/camloc"]
