[package]
name = "roblib-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro-error = { version = "1", default-features = false }
syn = { version = "2", features = ["full", "extra-traits"] }
proc-macro2 = "1" 
quote = "1"
